import type { Metadata } from "next";
import { Almarai } from "next/font/google";
import "./globals.css";
import Header from "./componet/header/Header";

const inter = Almarai({ weight: ["300","400","700"],subsets: ['arabic'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" dir="rtl">
      <body className={inter.className}>
        <Header/>
        {children}</body>
    </html>
  );
}
